plugins:
  - jekyll-seo-tag
  
collections:
  projects:
    output: true

social:
  name: –ê510
  links:
    - https://www.facebook.com/a510ru
    - http://instagram.com/a510ru

logo: /images/icon-512.png
url: https://a510.studio

title: ""
lang: "en_US"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/icon-512.png
